var color_data = [
			{ name:"aliceblue", value: "F0F8FF"},
{ name:"antiquewhite", value: "FAEBD7"},
{ name:"aqua", value: "00FFFF"},
{ name:"aquamarine", value: "7FFFD4"},
{ name:"azure", value: "F0FFFF"},
{ name:"beige", value: "F5F5DC"},
{ name:"bisque", value: "FFE4C4"},
{ name:"black", value: "000000"},
{ name:"blanchedalmond", value: "FFEBCD"},
{ name:"blue", value: "0000FF"},
{ name:"blueviolet", value: "8A2BE2"},
{ name:"brown", value: "A52A2A"},
{ name:"burlywood", value: "DEB887"},
{ name:"cadetblue", value: "5F9EA0"},
{ name:"chartreuse", value: "7FFF00"},
{ name:"chocolate", value: "D2691E"},
{ name:"coral", value: "FF7F50"},
{ name:"cornflowerblue", value: "6495ED"},
{ name:"cornsilk", value: "FFF8DC"},
{ name:"crimson", value: "DC143C"},
{ name:"cyan", value: "00FFFF"},
{ name:"darkblue", value: "00008B"},
{ name:"darkcyan", value: "008B8B"},
{ name:"darkgoldenrod", value: "B8860B"},
{ name:"darkgray", value: "A9A9A9"},
{ name:"darkgrey", value: "A9A9A9"},
{ name:"darkgreen", value: "006400"},
{ name:"darkkhaki", value: "BDB76B"},
{ name:"darkmagenta", value: "8B008B"},
{ name:"darkolivegreen", value: "556B2F"},
{ name:"darkorange", value: "FF8C00"},
{ name:"darkorchid", value: "9932CC"},
{ name:"darkred", value: "8B0000"},
{ name:"darksalmon", value: "E9967A"},
{ name:"darkseagreen", value: "8FBC8F"},
{ name:"darkslateblue", value: "483D8B"},
{ name:"darkslategray", value: "2F4F4F"},
{ name:"darkslategrey", value: "2F4F4F"},
{ name:"darkturquoise", value: "00CED1"},
{ name:"darkviolet", value: "9400D3"},
{ name:"deeppink", value: "FF1493"},
{ name:"deepskyblue", value: "00BFFF"},
{ name:"dimgray", value: "696969"},
{ name:"dimgrey", value: "696969"},
{ name:"dodgerblue", value: "1E90FF"},
{ name:"firebrick", value: "B22222"},
{ name:"floralwhite", value: "FFFAF0"},
{ name:"forestgreen", value: "228B22"},
{ name:"fuchsia", value: "FF00FF"},
{ name:"gainsboro", value: "DCDCDC"},
{ name:"ghostwhite", value: "F8F8FF"},
{ name:"gold", value: "FFD700"},
{ name:"goldenrod", value: "DAA520"},
{ name:"gray", value: "808080"},
{ name:"grey", value: "808080"},
{ name:"green", value: "008000"},
{ name:"greenyellow", value: "ADFF2F"},
{ name:"honeydew", value: "F0FFF0"},
{ name:"hotpink", value: "FF69B4"},
{ name:"indianred", value: "CD5C5C"},
{ name:"indigo", value: "4B0082"},
{ name:"ivory", value: "FFFFF0"},
{ name:"khaki", value: "F0E68C"},
{ name:"lavender", value: "E6E6FA"},
{ name:"lavenderblush", value: "FFF0F5"},
{ name:"lawngreen", value: "7CFC00"},
{ name:"lemonchiffon", value: "FFFACD"},
{ name:"lightblue", value: "ADD8E6"},
{ name:"lightcoral", value: "F08080"},
{ name:"lightcyan", value: "E0FFFF"},
{ name:"lightgoldenrodyellow", value: "FAFAD2"},
{ name:"lightgray", value: "D3D3D3"},
{ name:"lightgrey", value: "D3D3D3"},
{ name:"lightgreen", value: "90EE90"},
{ name:"lightpink", value: "FFB6C1"},
{ name:"lightsalmon", value: "FFA07A"},
{ name:"lightseagreen", value: "20B2AA"},
{ name:"lightskyblue", value: "87CEFA"},
{ name:"lightslategray", value: "778899"},
{ name:"lightslategrey", value: "778899"},
{ name:"lightsteelblue", value: "B0C4DE"},
{ name:"lightyellow", value: "FFFFE0"},
{ name:"lime", value: "00FF00"},
{ name:"limegreen", value: "32CD32"},
{ name:"linen", value: "FAF0E6"},
{ name:"magenta", value: "FF00FF"},
{ name:"maroon", value: "800000"},
{ name:"mediumaquamarine", value: "66CDAA"},
{ name:"mediumblue", value: "0000CD"},
{ name:"mediumorchid", value: "BA55D3"},
{ name:"mediumpurple", value: "9370D8"},
{ name:"mediumseagreen", value: "3CB371"},
{ name:"mediumslateblue", value: "7B68EE"},
{ name:"mediumspringgreen", value: "00FA9A"},
{ name:"mediumturquoise", value: "48D1CC"},
{ name:"mediumvioletred", value: "C71585"},
{ name:"midnightblue", value: "191970"},
{ name:"mintcream", value: "F5FFFA"},
{ name:"mistyrose", value: "FFE4E1"},
{ name:"moccasin", value: "FFE4B5"},
{ name:"navajowhite", value: "FFDEAD"},
{ name:"navy", value: "000080"},
{ name:"oldlace", value: "FDF5E6"},
{ name:"olive", value: "808000"},
{ name:"olivedrab", value: "6B8E23"},
{ name:"orange", value: "FFA500"},
{ name:"orangered", value: "FF4500"},
{ name:"orchid", value: "DA70D6"},
{ name:"palegoldenrod", value: "EEE8AA"},
{ name:"palegreen", value: "98FB98"},
{ name:"paleturquoise", value: "AFEEEE"},
{ name:"palevioletred", value: "D87093"},
{ name:"papayawhip", value: "FFEFD5"},
{ name:"peachpuff", value: "FFDAB9"},
{ name:"peru", value: "CD853F"},
{ name:"pink", value: "FFC0CB"},
{ name:"plum", value: "DDA0DD"},
{ name:"powderblue", value: "B0E0E6"},
{ name:"purple", value: "800080"},
{ name:"rebeccapurple", value: "663399"},
{ name:"red", value: "FF0000"},
{ name:"rosybrown", value: "BC8F8F"},
{ name:"royalblue", value: "4169E1"},
{ name:"saddlebrown", value: "8B4513"},
{ name:"salmon", value: "FA8072"},
{ name:"sandybrown", value: "F4A460"},
{ name:"seagreen", value: "2E8B57"},
{ name:"seashell", value: "FFF5EE"},
{ name:"sienna", value: "A0522D"},
{ name:"silver", value: "C0C0C0"},
{ name:"skyblue", value: "87CEEB"},
{ name:"slateblue", value: "6A5ACD"},
{ name:"slategray", value: "708090"},
{ name:"slategrey", value: "708090"},
{ name:"snow", value: "FFFAFA"},
{ name:"springgreen", value: "00FF7F"},
{ name:"steelblue", value: "4682B4"},
{ name:"tan", value: "D2B48C"},
{ name:"teal", value: "008080"},
{ name:"thistle", value: "D8BFD8"},
{ name:"tomato", value: "FF6347"},
{ name:"turquoise", value: "40E0D0"},
{ name:"violet", value: "EE82EE"},
{ name:"wheat", value: "F5DEB3"},
{ name:"white", value: "FFFFFF"},
{ name:"whitesmoke", value: "F5F5F5"},
{ name:"yellow", value: "FFFF00"},
{ name:"yellowgreen", value: "9ACD32"}
		];
		
		


color_data.sort(function (a,b) {
  if (a.value < b.value)
    return -1;
  if (a.value > b.value)
    return 1;
  return 0;
});



//                  GEN                   //
const SORTED_COLOR_CODE = [{"name":"black","value":"000000"},{"name":"navy","value":"000080"},{"name":"darkblue","value":"00008B"},{"name":"mediumblue","value":"0000CD"},{"name":"blue","value":"0000FF"},{"name":"darkgreen","value":"006400"},{"name":"green","value":"008000"},{"name":"teal","value":"008080"},{"name":"darkcyan","value":"008B8B"},{"name":"deepskyblue","value":"00BFFF"},{"name":"darkturquoise","value":"00CED1"},{"name":"mediumspringgreen","value":"00FA9A"},{"name":"lime","value":"00FF00"},{"name":"springgreen","value":"00FF7F"},{"name":"cyan","value":"00FFFF"},{"name":"aqua","value":"00FFFF"},{"name":"midnightblue","value":"191970"},{"name":"dodgerblue","value":"1E90FF"},{"name":"lightseagreen","value":"20B2AA"},{"name":"forestgreen","value":"228B22"},{"name":"seagreen","value":"2E8B57"},{"name":"darkslategrey","value":"2F4F4F"},{"name":"darkslategray","value":"2F4F4F"},{"name":"limegreen","value":"32CD32"},{"name":"mediumseagreen","value":"3CB371"},{"name":"turquoise","value":"40E0D0"},{"name":"royalblue","value":"4169E1"},{"name":"steelblue","value":"4682B4"},{"name":"darkslateblue","value":"483D8B"},{"name":"mediumturquoise","value":"48D1CC"},{"name":"indigo","value":"4B0082"},{"name":"darkolivegreen","value":"556B2F"},{"name":"cadetblue","value":"5F9EA0"},{"name":"cornflowerblue","value":"6495ED"},{"name":"rebeccapurple","value":"663399"},{"name":"mediumaquamarine","value":"66CDAA"},{"name":"dimgrey","value":"696969"},{"name":"dimgray","value":"696969"},{"name":"slateblue","value":"6A5ACD"},{"name":"olivedrab","value":"6B8E23"},{"name":"slategray","value":"708090"},{"name":"slategrey","value":"708090"},{"name":"lightslategrey","value":"778899"},{"name":"lightslategray","value":"778899"},{"name":"mediumslateblue","value":"7B68EE"},{"name":"lawngreen","value":"7CFC00"},{"name":"chartreuse","value":"7FFF00"},{"name":"aquamarine","value":"7FFFD4"},{"name":"maroon","value":"800000"},{"name":"purple","value":"800080"},{"name":"olive","value":"808000"},{"name":"gray","value":"808080"},{"name":"grey","value":"808080"},{"name":"skyblue","value":"87CEEB"},{"name":"lightskyblue","value":"87CEFA"},{"name":"blueviolet","value":"8A2BE2"},{"name":"darkred","value":"8B0000"},{"name":"darkmagenta","value":"8B008B"},{"name":"saddlebrown","value":"8B4513"},{"name":"darkseagreen","value":"8FBC8F"},{"name":"lightgreen","value":"90EE90"},{"name":"mediumpurple","value":"9370D8"},{"name":"darkviolet","value":"9400D3"},{"name":"palegreen","value":"98FB98"},{"name":"darkorchid","value":"9932CC"},{"name":"yellowgreen","value":"9ACD32"},{"name":"sienna","value":"A0522D"},{"name":"brown","value":"A52A2A"},{"name":"darkgray","value":"A9A9A9"},{"name":"darkgrey","value":"A9A9A9"},{"name":"lightblue","value":"ADD8E6"},{"name":"greenyellow","value":"ADFF2F"},{"name":"paleturquoise","value":"AFEEEE"},{"name":"lightsteelblue","value":"B0C4DE"},{"name":"powderblue","value":"B0E0E6"},{"name":"firebrick","value":"B22222"},{"name":"darkgoldenrod","value":"B8860B"},{"name":"mediumorchid","value":"BA55D3"},{"name":"rosybrown","value":"BC8F8F"},{"name":"darkkhaki","value":"BDB76B"},{"name":"silver","value":"C0C0C0"},{"name":"mediumvioletred","value":"C71585"},{"name":"indianred","value":"CD5C5C"},{"name":"peru","value":"CD853F"},{"name":"chocolate","value":"D2691E"},{"name":"tan","value":"D2B48C"},{"name":"lightgrey","value":"D3D3D3"},{"name":"lightgray","value":"D3D3D3"},{"name":"palevioletred","value":"D87093"},{"name":"thistle","value":"D8BFD8"},{"name":"orchid","value":"DA70D6"},{"name":"goldenrod","value":"DAA520"},{"name":"crimson","value":"DC143C"},{"name":"gainsboro","value":"DCDCDC"},{"name":"plum","value":"DDA0DD"},{"name":"burlywood","value":"DEB887"},{"name":"lightcyan","value":"E0FFFF"},{"name":"lavender","value":"E6E6FA"},{"name":"darksalmon","value":"E9967A"},{"name":"violet","value":"EE82EE"},{"name":"palegoldenrod","value":"EEE8AA"},{"name":"lightcoral","value":"F08080"},{"name":"khaki","value":"F0E68C"},{"name":"aliceblue","value":"F0F8FF"},{"name":"honeydew","value":"F0FFF0"},{"name":"azure","value":"F0FFFF"},{"name":"sandybrown","value":"F4A460"},{"name":"wheat","value":"F5DEB3"},{"name":"beige","value":"F5F5DC"},{"name":"whitesmoke","value":"F5F5F5"},{"name":"mintcream","value":"F5FFFA"},{"name":"ghostwhite","value":"F8F8FF"},{"name":"salmon","value":"FA8072"},{"name":"antiquewhite","value":"FAEBD7"},{"name":"linen","value":"FAF0E6"},{"name":"lightgoldenrodyellow","value":"FAFAD2"},{"name":"oldlace","value":"FDF5E6"},{"name":"red","value":"FF0000"},{"name":"fuchsia","value":"FF00FF"},{"name":"magenta","value":"FF00FF"},{"name":"deeppink","value":"FF1493"},{"name":"orangered","value":"FF4500"},{"name":"tomato","value":"FF6347"},{"name":"hotpink","value":"FF69B4"},{"name":"coral","value":"FF7F50"},{"name":"darkorange","value":"FF8C00"},{"name":"lightsalmon","value":"FFA07A"},{"name":"orange","value":"FFA500"},{"name":"lightpink","value":"FFB6C1"},{"name":"pink","value":"FFC0CB"},{"name":"gold","value":"FFD700"},{"name":"peachpuff","value":"FFDAB9"},{"name":"navajowhite","value":"FFDEAD"},{"name":"moccasin","value":"FFE4B5"},{"name":"bisque","value":"FFE4C4"},{"name":"mistyrose","value":"FFE4E1"},{"name":"blanchedalmond","value":"FFEBCD"},{"name":"papayawhip","value":"FFEFD5"},{"name":"lavenderblush","value":"FFF0F5"},{"name":"seashell","value":"FFF5EE"},{"name":"cornsilk","value":"FFF8DC"},{"name":"lemonchiffon","value":"FFFACD"},{"name":"floralwhite","value":"FFFAF0"},{"name":"snow","value":"FFFAFA"},{"name":"yellow","value":"FFFF00"},{"name":"lightyellow","value":"FFFFE0"},{"name":"ivory","value":"FFFFF0"},{"name":"white","value":"FFFFFF"}];


//                RAW DATA                //

//var color_data = {
//			aliceblue: "F0F8FF",
//			antiquewhite: "FAEBD7",
//			aqua: "00FFFF",
//			aquamarine: "7FFFD4",
//			azure: "F0FFFF",
//			beige: "F5F5DC",
//			bisque: "FFE4C4",
//			black: "000000",
//			blanchedalmond: "FFEBCD",
//			blue: "0000FF",
//			blueviolet: "8A2BE2",
//			brown: "A52A2A",
//			burlywood: "DEB887",
//			cadetblue: "5F9EA0",
//			chartreuse: "7FFF00",
//			chocolate: "D2691E",
//			coral: "FF7F50",
//			cornflowerblue: "6495ED",
//			cornsilk: "FFF8DC",
//			crimson: "DC143C",
//			cyan: "00FFFF",
//			darkblue: "00008B",
//			darkcyan: "008B8B",
//			darkgoldenrod: "B8860B",
//			darkgray: "A9A9A9",
//			darkgrey: "A9A9A9",
//			darkgreen: "006400",
//			darkkhaki: "BDB76B",
//			darkmagenta: "8B008B",
//			darkolivegreen: "556B2F",
//			darkorange: "FF8C00",
//			darkorchid: "9932CC",
//			darkred: "8B0000",
//			darksalmon: "E9967A",
//			darkseagreen: "8FBC8F",
//			darkslateblue: "483D8B",
//			darkslategray: "2F4F4F",
//			darkslategrey: "2F4F4F",
//			darkturquoise: "00CED1",
//			darkviolet: "9400D3",
//			deeppink: "FF1493",
//			deepskyblue: "00BFFF",
//			dimgray: "696969",
//			dimgrey: "696969",
//			dodgerblue: "1E90FF",
//			firebrick: "B22222",
//			floralwhite: "FFFAF0",
//			forestgreen: "228B22",
//			fuchsia: "FF00FF",
//			gainsboro: "DCDCDC",
//			ghostwhite: "F8F8FF",
//			gold: "FFD700",
//			goldenrod: "DAA520",
//			gray: "808080",
//			grey: "808080",
//			green: "008000",
//			greenyellow: "ADFF2F",
//			honeydew: "F0FFF0",
//			hotpink: "FF69B4",
//			indianred: "CD5C5C",
//			indigo: "4B0082",
//			ivory: "FFFFF0",
//			khaki: "F0E68C",
//			lavender: "E6E6FA",
//			lavenderblush: "FFF0F5",
//			lawngreen: "7CFC00",
//			lemonchiffon: "FFFACD",
//			lightblue: "ADD8E6",
//			lightcoral: "F08080",
//			lightcyan: "E0FFFF",
//			lightgoldenrodyellow: "FAFAD2",
//			lightgray: "D3D3D3",
//			lightgrey: "D3D3D3",
//			lightgreen: "90EE90",
//			lightpink: "FFB6C1",
//			lightsalmon: "FFA07A",
//			lightseagreen: "20B2AA",
//			lightskyblue: "87CEFA",
//			lightslategray: "778899",
//			lightslategrey: "778899",
//			lightsteelblue: "B0C4DE",
//			lightyellow: "FFFFE0",
//			lime: "00FF00",
//			limegreen: "32CD32",
//			linen: "FAF0E6",
//			magenta: "FF00FF",
//			maroon: "800000",
//			mediumaquamarine: "66CDAA",
//			mediumblue: "0000CD",
//			mediumorchid: "BA55D3",
//			mediumpurple: "9370D8",
//			mediumseagreen: "3CB371",
//			mediumslateblue: "7B68EE",
//			mediumspringgreen: "00FA9A",
//			mediumturquoise: "48D1CC",
//			mediumvioletred: "C71585",
//			midnightblue: "191970",
//			mintcream: "F5FFFA",
//			mistyrose: "FFE4E1",
//			moccasin: "FFE4B5",
//			navajowhite: "FFDEAD",
//			navy: "000080",
//			oldlace: "FDF5E6",
//			olive: "808000",
//			olivedrab: "6B8E23",
//			orange: "FFA500",
//			orangered: "FF4500",
//			orchid: "DA70D6",
//			palegoldenrod: "EEE8AA",
//			palegreen: "98FB98",
//			paleturquoise: "AFEEEE",
//			palevioletred: "D87093",
//			papayawhip: "FFEFD5",
//			peachpuff: "FFDAB9",
//			peru: "CD853F",
//			pink: "FFC0CB",
//			plum: "DDA0DD",
//			powderblue: "B0E0E6",
//			purple: "800080",
//			rebeccapurple: "663399",
//			red: "FF0000",
//			rosybrown: "BC8F8F",
//			royalblue: "4169E1",
//			saddlebrown: "8B4513",
//			salmon: "FA8072",
//			sandybrown: "F4A460",
//			seagreen: "2E8B57",
//			seashell: "FFF5EE",
//			sienna: "A0522D",
//			silver: "C0C0C0",
//			skyblue: "87CEEB",
//			slateblue: "6A5ACD",
//			slategray: "708090",
//			slategrey: "708090",
//			snow: "FFFAFA",
//			springgreen: "00FF7F",
//			steelblue: "4682B4",
//			tan: "D2B48C",
//			teal: "008080",
//			thistle: "D8BFD8",
//			tomato: "FF6347",
//			turquoise: "40E0D0",
//			violet: "EE82EE",
//			wheat: "F5DEB3",
//			white: "FFFFFF",
//			whitesmoke: "F5F5F5",
//			yellow: "FFFF00",
//			yellowgreen: "9ACD32"
//		};